export const TAGS = ["Work", "Health", "Money", "Love", "Mind", "Other"];

export const LANGUAGES = [
  { code: "en-IN", label: "English (India)" },
  { code: "en-US", label: "English (US)" },
  { code: "en-GB", label: "English (UK)" },
  { code: "hi-IN", label: "Hindi" },
  { code: "mr-IN", label: "Marathi" },
  { code: "bn-IN", label: "Bengali" },
  { code: "ta-IN", label: "Tamil" },
  { code: "te-IN", label: "Telugu" },
  { code: "pa-IN", label: "Punjabi" },
  { code: "ur-PK", label: "Urdu" },
  { code: "es-ES", label: "Spanish" },
  { code: "fr-FR", label: "French" },
  { code: "de-DE", label: "German" },
  { code: "pt-BR", label: "Portuguese (BR)" },
  { code: "ar-SA", label: "Arabic" },
  { code: "zh-CN", label: "Chinese (CN)" },
  { code: "ja-JP", label: "Japanese" },
  { code: "ko-KR", label: "Korean" },
  { code: "ru-RU", label: "Russian" },
  { code: "it-IT", label: "Italian" },
];

export const TEM = {
  Work: "💼",
  Health: "🫀",
  Money: "💸",
  Love: "💛",
  Mind: "🧠",
  Other: "✦",
};

export const STRINGS = {
  en: {
    greeting_morning: "Good morning",
    greeting_afternoon: "Good afternoon",
    greeting_evening: "Good evening",
    greeting_night: "Still up,",
    stat_victories: "Victories",
    stat_streak: "Day streak",
    stat_week: "This week",
    tap_hint: "Log a victory",
    recording: "Recording…",
    transcribing: "Transcribing…",
    speak_ph: "Begin speaking…",
    edit_hint: "Tap above to fix any errors before saving",
    tag_lbl: "Tag this win (optional)",
    stack: "Stack it ✦",
    discard: "Discard",
    spiral_btn: "⟳    I'm spiraling — remind me who I am",
    spiral_sub: "Shows your own victories when doubt kicks in",
    recent: "Recent victories",
    share_nudge: "Share this win →",
    search_ph: "Search your victories…",
    months: [
      "January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December",
    ],
    days: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
    anchors: [
      "What did you believe about yourself when this happened?",
      "What strength made this possible?",
      "What would you tell a friend who doubted they could do this?",
      "How did it feel in the moment you realized it worked?",
      "What fear did you push through to get here?",
      "What changed in you after this victory?",
      "Who believed in you when this happened?",
      "What would past-you think seeing you accomplish this?",
    ],
    sample_win:
      "I opened Victory Journal and decided to start tracking my wins. That took courage.",
    victory: "victory",
    victories: "victories",
    victories_in: "victories in",
    no_wins_home: "Your first victory is waiting to be recorded. Tap the mic above.",
    no_wins_month: "No victories this month yet.",
    no_wins_search: "No victories match that search.",
    grace: "✦ grace day active — log a win today",
    empty_spiral:
      "Record your first victory — then come back here when you need a reminder.",
    back: "Back",
    del_body:
      "Victories, once lived, cannot be unlived. This will permanently remove it from your journal.",
    del_keep: "Keep it",
    del_remove: "Remove it",
    clr_body:
      "This permanently deletes all your victories. Export your data first if you want a backup.",
    clr_cancel: "Cancel",
    clr_yes: "Yes, clear all",
    settings_lang: "Language",
    settings_install: "Install",
    settings_danger: "Danger zone",
    settings_data: "Your data",
  },
};
